/* cpnos-rom BIOS implementation (RAM-resident).
 *
 * Linked into the payload at 0xED00+ as part of the single-blob build.
 * Relocator reconstructs the payload from both EPROMs on cold boot
 * (see relocator.s, payload.ld).  Code here starts executing after
 * cpnos_main.c's _cpnos_cold_entry has done PROM disable, zero-page
 * setup, SNIOS wiring, and JP to 0xD000.
 *
 * Contents: BIOS jump-table implementations (CONOUT control codes,
 * keyboard ring, disk stubs, boot/warm-boot handlers).
 */

#include <stdint.h>
#include <stddef.h>
#include "hal.h"
#include "compiler/compat.h"

/* Historical section tag: keeps these symbols in `.resident`, which
 * the payload linker script places at the start of the payload so
 * the BIOS jump table lands at 0xED00 (ABI-fixed).  The section
 * attribute only applies under the ELF compile path; macOS system
 * clang (Mach-O, driving the IDE's LSP) rejects it. */
#ifdef __ELF__
#define RESIDENT __attribute__((section(".resident"), used))
#else
#define RESIDENT
#endif

#if MIRROR_SIOB
/* Busy-wait SIO-B transmit.  Used by impl_conout to mirror every
 * console byte to the null-modem log. */
RESIDENT
static void console_putc(uint8_t c) {
    while ((IO_READ(SIO_B_CTRL) & SIO_RR0_TX_BUF_EMPTY) == 0) { }
    IO_WRITE(SIO_B_DATA, c);
}
#endif

/* -------------------------------------------------------------------
 * BIOS jump-table implementations.
 *
 * Targets of the `jp nn` entries in bios_jt.s.  Names follow the
 * pattern `impl_<entry>` so the linker resolves the asm references.
 * ------------------------------------------------------------------- */

/* SDCC's link of an empty `void f(void) { }` placed bios_stub_ret in
 * z88dk's code_l_sccz80 runtime-library section near 0xEDF4 — outside
 * the PROM-loaded resident range, so JP _bios_stub_ret landed in
 * uninitialised RAM and eventually wrapped to a JP-0 warm-boot loop.
 * For SDCC the symbol is now defined directly in sdcc/bios_jt.asm
 * (lives in RESIDENT_JUMPTABLE).  Clang has no such issue and keeps
 * the C version. */
#ifdef __clang__
RESIDENT
void bios_stub_ret(void) { }
#endif

/* Re-enter NDOS COLDST.  cpnos.com starts at NDOS with NDOS+0 = JP
 * NDOSE (BDOS dispatch) and NDOS+3 = COLDST.  Setting SP back to the
 * CP/M-convention TPA top (0x0100) before the jump matches what
 * cpnos_cold_entry's tail does on first boot.  CPNOS_NDOS_ADDR is
 * extracted from cpnos.sym at PROM build time (clang/cpnos_addrs.h),
 * so this stays right whenever cpnos-build's CODE_BASE moves. */
#include "cpnos_addrs.h"
RESIDENT
NORETURN void enter_coldst(void) {
    /* CPNOS_NDOSE_ADDR = NDOS + 3 (the BDOS dispatch entry inside
     * cpnos.com).  Generated by the Makefile from cpnos.sym so it
     * tracks whatever address NDOS actually links at.  Stringified
     * here — both compilers accept `jp 0xC0E1` literal syntax.  The
     * earlier clang `%0` operand-substitution was clang-only. */
    ASM_VOLATILE(
        "ld sp, 0x0100\n\t"
        "jp " CPNOS_STR(CPNOS_NDOSE_ADDR) "\n\t"
    );
    __builtin_unreachable();
}

RESIDENT
NORETURN void impl_boot(void) {
    /* CP/M cold-boot entry.  cpnos_main tail-called resident_entry
     * directly once already, so the normal boot flow doesn't come
     * through here.  If CP/NOS itself ever jumps here (e.g. during
     * its post-handoff init before it has patched the zero page
     * to point at NDOSRL's BIOS JT), re-enter NDOS COLDST.  Was Issue U. */
    enter_coldst();
}

RESIDENT
NORETURN void impl_wboot(void) {
    /* CP/M warm boot.  In CP/NOS the whole OS image is in RAM and
     * re-runnable from COLDST, which re-fetches CCP.SPR via NDOS.
     *
     * Test instrumentation: emit a port-0x81 write so MAME Lua taps
     * can count program exits without scraping the screen.  Port 0x81
     * is in RC702's unmapped 0x20-0xEF range (rc702.cpp:155-163), so
     * there is no contention on real hardware either; on a stock
     * machine the OUT is a no-op.  Used by smoke_inject's "wait until
     * Nth program has exited" detection.  4 bytes (3E 57 D3 81),
     * 18 T-states.  Value 0x57 = 'W' for "Warm boot" -- only the
     * write event is meaningful, not the data byte. */
    /* Function is NORETURN, so the A clobber doesn't matter — the
     * caller never sees us return.  Drop the clobber list so SDCC's
     * parser accepts the body. */
    ASM_VOLATILE("ld a, 0x57\n\t out (0x81), a\n\t");
    enter_coldst();
}

/* PIO-A keyboard ring buffer.  Populated by isr_pio_kbd (isr.s) on each
 * PIO-A interrupt — one keystroke per IRQ.  Drained by impl_conin.
 * Size must be a power of two (mask = SIZE-1).  SIO-B RX is checked
 * first so automated tests driving the serial line see predictable
 * byte ordering; the PIO path only matters when a human types at the
 * physical keyboard, and the ring smooths over the ISR<->poll race. */
#define KBD_RING_SIZE 16
uint8_t kbd_ring[KBD_RING_SIZE];
uint8_t kbd_head;   /* written by ISR */
uint8_t kbd_tail;   /* written by CONIN */

/* Legacy harness counters from the polled-PIO bring-up phase.  Replaced
 * by pio_rx_buf/head/tail (transport_pio.c) when the IRQ ring landed in
 * commit f10c99f.  Kept (with `used`) because tests/cpnet_bridge/
 * harness.py extracts their addresses from payload.elf and treats them
 * as required symbols — dropping them via --gc-sections breaks the
 * harness's pre-MAME symbol-extraction step.  Two BSS bytes; readers
 * see permanent zero, which is fine for pio-netboot mode (success is
 * the boot-strip 'J', not these counters). */
USED uint8_t pio_par_byte;
USED uint8_t pio_par_count;

/* boot_probe / p_hex / probe_once / bios_log_byte / bios_log_buf
 * removed in #72 -- issues #57 + #60 closed.  -146 B RESIDENT_CODE
 * + 220 B unused IVT-page padding freed.  See #72 closing comment for
 * the linker layout fix that this removal also required (RESIDENT_
 * CHECKSUM section in sdcc/sections.asm). */

/* Install locale tables from the cpnos.img prefix.  Runs in
 * resident_handoff (cpnos_main.c) right after PROM disable.
 * Source = IMG_BASE (CPNOS_NDOS_ADDR - 384 when sentinel set, else
 * CPNOS_NDOS_ADDR -- in the unset case the source bytes are random
 * RAM and we MUST NOT copy them, hence the sentinel guard).
 * Destination = 0xF680..0xF7FF (outcon[128] + inconv[256], rcbios-
 * compatible layout, freed by clang-prom1lineprog/payload.ld v3). */
RESIDENT
void install_locale_tables(void) {
    extern uint8_t prom1_only_sentinel;
    if (prom1_only_sentinel != 0x5A) return;
    __builtin_memcpy((void *)0xF680,
                     (const void *)(CPNOS_NDOS_ADDR - 384),
                     384);
}

/* Resident helper that returns the netboot LDIR destination -- shifted
 * by 384 B on PROM1-only (sentinel set, cpnos.img has locale prefix),
 * unchanged on two-PROM (sentinel zero).  Called from init.c::netboot_mpm
 * so the branch logic lives in .resident, NOT in .init (which is at its
 * 640 B cap). */
RESIDENT
uint8_t *get_img_base(void) {
    extern uint8_t prom1_only_sentinel;
    return (uint8_t *)(prom1_only_sentinel == 0x5A
                       ? CPNOS_NDOS_ADDR - 384
                       : CPNOS_NDOS_ADDR);
}

RESIDENT
static uint8_t impl_const(void) {
    if (IO_READ(SIO_B_CTRL) & SIO_RR0_RX_CHAR_AVAIL) {
        return 0xFF;
    }
    if (kbd_head != kbd_tail) {
        return 0xFF;
    }
    return 0x00;
}

/* -------------------------------------------------------------------
 * CRT CONOUT — RC700 control code set.
 *
 * Ported from rcbios-in-c/bios.c:specc().  Skips bg/fg overlay codes
 * (0x13/14/15) — they need a BGSTAR bitmap CP/NOS doesn't carry.
 *
 *   0x01 insert line        0x0C clear screen
 *   0x02 delete line        0x0D carriage return
 *   0x05 cursor left (ENQ)  0x18 cursor right
 *   0x06 XY cursor addr     0x1A cursor up
 *   0x07 bell               0x1D home
 *   0x08 cursor left (BS)   0x1E erase to EOL
 *   0x09 TAB (4 rights)     0x1F erase to EOS
 *   0x0A cursor down
 * ------------------------------------------------------------------- */

#define SCRN_COLS 80
#define SCRN_ROWS 25

/* Cursor + XY-addressing state.  Lives in .scratch_bss (zero-init).
 *
 * curx / cury / cur_dirty are non-static so _isr_crt (in isr.s) can
 * reference them directly — the ISR consumes cur_dirty to reprogram
 * the 8275 cursor registers once per vertical retrace instead of on
 * every CONOUT, which was visibly flickering under fast streams. */
uint8_t curx;                 /* 0..79 */
uint8_t cury;                 /* 0..24 */
uint8_t cur_dirty;            /* set by impl_conout, cleared by _isr_crt */
/* SW1 bit 0 (S01) sampled once in cpnos_cold_entry (init.c).
 *   1 = joined console: SIO-B + keyboard input, SIO-B + CRT output
 *       (matches MAME "On" = SW1 bit cleared; default).
 *   0 = local-only: keyboard input + CRT output, SIO-B ignored.
 * Read once because impl_conin / impl_conout are hot. */
uint8_t console_joined;

/* PROM1-only build sentinel.  PROM1-only's bootstrap.s writes 0x5A
 * here right after ZX0-decompressing the resident, before jp to
 * cpnos_cold_entry.  Shared init.c / resident.c code reads this to
 * decide whether to apply the locale-table install path (IMG_BASE
 * shifted by 384 B so cpnos.img can prepend an outcon[128]+inconv[256]
 * locale prefix; install_locale_tables LDIRs the prefix to its runtime
 * home at 0xF680..0xF7FF; impl_conout/conin use the tables).
 *
 * Two-PROM cold-init never writes this byte (BSS stays zero), so all
 * locale paths short-circuit to a no-op on two-PROM.  The PROM1-only
 * RAM layout (clang-prom1lineprog/payload.ld) is the one that puts
 * the freed 0xF680..0xF7FF region above pio_rx_buf at 0xEC00 -- on
 * two-PROM 0xF700..0xF7FF is still pio_rx_buf and writes there would
 * corrupt the IRQ ring. */
uint8_t prom1_only_sentinel;
static uint8_t xflg;          /* 0 = normal; 2/1 = awaiting XY coord bytes */
static uint8_t xy_first;      /* first coord saved between XY calls */

/* screen[row*80 + col].  Macro avoids a function-call overhead at each
 * site (clang-z80 doesn't inline small helpers reliably at -Oz). */
#define CELL(x, y)  ((uint8_t *)DISPLAY_ADDR + (uint16_t)(y) * SCRN_COLS + (x))

/* noinline: clang -Oz inlines the LDIR body into both cursor_right and
 * cursor_down, costing ~25 B of duplicated scroll code on top of the
 * standalone symbol.  Forcing one call site shares the body. */
RESIDENT
static NOINLINE void scroll_up(void) {
    /* Move rows 1..24 to 0..23, blank row 24. */
    uint8_t *d = (uint8_t *)DISPLAY_ADDR;
    __builtin_memcpy(d, d + SCRN_COLS, (SCRN_ROWS - 1) * (unsigned)SCRN_COLS);
    __builtin_memset(CELL(0, SCRN_ROWS - 1), ' ', SCRN_COLS);
}

/* --- cursor movement ---------------------------------------------- */

RESIDENT
static void cursor_right(void) {
    if (++curx < SCRN_COLS) return;
    curx = 0;
    if (cury + 1 < SCRN_ROWS) cury++;
    else scroll_up();
}

RESIDENT
static void cursor_left(void) {
    if (curx != 0) { curx--; return; }
    curx = SCRN_COLS - 1;
    cury = (cury != 0) ? cury - 1 : SCRN_ROWS - 1;
}

RESIDENT
static void cursor_down(void) {
    if (cury + 1 < SCRN_ROWS) cury++;
    else scroll_up();
}

RESIDENT
static void cursor_up(void) {
    cury = (cury != 0) ? cury - 1 : SCRN_ROWS - 1;
}

RESIDENT
static void home(void) { curx = 0; cury = 0; }

RESIDENT
static void tab(void) {
    cursor_right(); cursor_right(); cursor_right(); cursor_right();
}

/* --- screen ops --------------------------------------------------- */

RESIDENT
/* Non-static so init.c can CALL us at cold-boot instead of inlining
 * a second LDIR-based memset of the 2000-byte display region. */
void clear_screen(void) {
    __builtin_memset((void *)DISPLAY_ADDR, ' ',
                     (unsigned)SCRN_ROWS * SCRN_COLS);
    home();
}

/* erase_to_eol / erase_to_eos: variable-length space-fill into display
 * memory.  Hand-rolled byte loop instead of __builtin_memset because
 * z88dk-zsdcc 4.5.0 doesn't inline-fold __builtin_memset with a
 * runtime-computed count -- it lowers to a `_memset` libc call (28 B
 * resident: 11 B trampoline + 17 B asm body).  A direct byte loop
 * compiles tighter on both compilers AND avoids the libcall (#70). */
RESIDENT
static void erase_to_eol(void) {
    uint8_t *p   = CELL(curx, cury);
    uint8_t *end = CELL(0, cury) + SCRN_COLS;
    while (p != end) *p++ = ' ';
}

RESIDENT
static void erase_to_eos(void) {
    uint8_t *p   = CELL(curx, cury);
    uint8_t *end = CELL(0, SCRN_ROWS - 1) + SCRN_COLS;
    while (p != end) *p++ = ' ';
}

/* Shared scroll: shift the lines below cury one row up (`up=1`,
 * delete_line) or down (`up=0`, insert_line), then blank the
 * vacated row.  Both control codes share enough structure
 * (count = (24-cury)*80; conditional copy; memset of one row)
 * that one body + branch saves bytes vs two 75-byte functions. */
RESIDENT
NOINLINE static void scroll_lines(uint8_t up) {
    uint8_t *row = CELL(0, cury);
    if (cury + 1 < SCRN_ROWS) {
        size_t count = (size_t)(SCRN_ROWS - 1 - cury) * SCRN_COLS;
        if (up) {
            __builtin_memcpy(row, row + SCRN_COLS, count);
        } else {
            /* Backward copy: regions overlap with dst > src.  Use
             * mem_copy_backwards (compat.h) instead of memmove —
             * bypasses the SDCC libc 13 B direction-check preamble. */
            uint8_t *src_e = row + count - 1;
            mem_copy_backwards(src_e + SCRN_COLS, src_e, count);
        }
    }
    __builtin_memset(up ? CELL(0, SCRN_ROWS - 1) : row, ' ', SCRN_COLS);
}

RESIDENT
static void delete_line(void) { scroll_lines(1); }

RESIDENT
static void insert_line(void) { scroll_lines(0); }

/* --- XY addressing (ctrl-F, then two coord bytes) ----------------- */

RESIDENT
static void start_xy(void) { xflg = 2; home(); }

RESIDENT
static void xy_step(uint8_t c) {
    uint8_t val = (c & 0x7F) - 32;       /* coord bytes are offset by ' ' */
    if (--xflg != 0) {
        xy_first = val;                  /* first byte: save X */
        return;
    }
    /* Second byte: Y, then place cursor.  Out-of-range coord bytes
     * clamp to 0 — the previous 3×-unrolled "mod SCRN_ROWS" could
     * not reach val < 25 from e.g. val=224 (raw binary 0 sent as
     * coord underflows), and the resulting wild val made CELL()
     * write outside display RAM.  Clamp is safer and smaller. */
    if (val >= SCRN_ROWS)      val = 0;
    if (xy_first >= SCRN_COLS) xy_first = 0;
    curx = xy_first;
    cury = val;
}

/* --- control-byte dispatch (0x00..0x1F) --------------------------- */

RESIDENT
static void specc(uint8_t c) {
    /* Ordered if/else chain, frequency-first.  Each branch lowers to a
     * single `cp N; jp Z, _handler` (5 B) via SDCC's tail-call peephole
     * + the orphan-jp cleanup added in ravn/z88dk#8 (peep 149a/b).
     * Smaller and faster on the hot controls than the prior numeric
     * `switch` (which SDCC laid out as a compare chain anyway, but
     * with the numerically-lowest cases in front -- 0x01/0x02 are the
     * rarest controls of all, so they punished every more-common one).
     * CR/LF kept at the bottom defensively: cpnos's impl_conout filters
     * them upstream so they shouldn't reach here, but rcbios may call
     * the same routine without that filter (future port). */
    if      (c == 0x08) cursor_left();      /* BS  -- common */
    else if (c == 0x09) tab();              /* HT  -- common */
    else if (c == 0x0C) clear_screen();     /* FF  -- common (PolyPascal blanks) */
    else if (c == 0x07) IO_WRITE(BIB, 0);   /* BEL -- moderately common */
    else if (c == 0x1D) home();             /* GS  -- cursor home */
    else if (c == 0x1E) erase_to_eol();     /* RS */
    else if (c == 0x1F) erase_to_eos();     /* US */
    else if (c == 0x18) cursor_right();     /* CAN -- cursor right */
    else if (c == 0x1A) cursor_up();        /* SUB -- cursor up */
    else if (c == 0x05) cursor_left();      /* ENQ -- BS alias */
    else if (c == 0x06) start_xy();         /* ACK -- XY-pos state mach */
    else if (c == 0x01) insert_line();      /* SOH */
    else if (c == 0x02) delete_line();      /* STX */
    else if (c == 0x0A) cursor_down();      /* LF  -- defensive (filtered) */
    else if (c == 0x0D) curx = 0;           /* CR  -- defensive (filtered) */
    /* else: unhandled control byte -- drop. */
}

/* --- public CONIN / CONOUT ---------------------------------------- */

/* Deferred-cursor flush helper.  Mirrors the tail of _isr_crt: if
 * cur_dirty is set, push curx/cury into the 8275 cursor registers
 * and clear the flag.  Called from impl_conin so that whoever is
 * about to wait for keystrokes sees the block cursor at the actual
 * logical position immediately, not one VRTC frame (~20ms) later
 * once isr_crt happens to fire.  Race vs isr_crt is benign: at
 * worst both paths sync to the same curx/cury and clear the flag
 * twice.  Same bytes as the ISR's cursor block, factored out so a
 * future refactor can have isr_crt CALL this too.
 *
 * Was hand-written in `__naked` asm to avoid clang's prologue/epilogue
 * cost.  Post-compiler-fixes (session 73j-late) the C form generates
 * identical or better code -- recent peepholes (#148 dec/inc-a for
 * equality, #144 i1 width, #142 high-byte zero) cover the patterns
 * this function uses.  Kept as plain C for source clarity. */
RESIDENT
static void sync_cursor_if_dirty(void) {
    if (cur_dirty) {
        cur_dirty = 0;
        IO_WRITE(CRT_CMD, 0x80);     /* 8275 'load cursor position' */
        IO_WRITE(CRT_PARAM, curx);
        IO_WRITE(CRT_PARAM, cury);
    }
}

RESIDENT
uint8_t impl_conin(void) {
    /* Flush any deferred cursor update before blocking — at a prompt
     * the operator expects the block cursor at the typing position
     * immediately, not on the next VRTC. */
    sync_cursor_if_dirty();

    /* inconv[256] at 0xF700: Danish-keyboard input table.  Only
     * referenced when prom1_only_sentinel == 0x5A (PROM1-only build
     * with locale prefix installed).  Pass-through otherwise. */
    const uint8_t *inconv = (const uint8_t *)0xF700;
    uint8_t use_inconv = (prom1_only_sentinel == 0x5A);
    for (;;) {
        if (console_joined &&
            (IO_READ(SIO_B_CTRL) & SIO_RR0_RX_CHAR_AVAIL)) {
            uint8_t c = IO_READ(SIO_B_DATA);
            return use_inconv ? inconv[c] : c;
        }
        if (kbd_head != kbd_tail) {
            uint8_t c = kbd_ring[kbd_tail];
            kbd_tail = (kbd_tail + 1) & (KBD_RING_SIZE - 1);
            return use_inconv ? inconv[c] : c;
        }
    }
}

RESIDENT
void impl_conout(uint8_t c) {
#if MIRROR_SIOB
    /* Serial mirror first — captures the raw byte stream for null-modem
     * logs regardless of what we do to the CRT side.  Runtime-gated on
     * SW1 bit 0 (console_joined): operator picks local-only vs. joined
     * console at boot without rebuilding the PROM. */
    if (console_joined) {
        console_putc(c);
    }
#endif

    /* Branch order tuned for CCP-style streaming where ~99% of bytes
     * are printable ASCII (>= 0x20) and the few control codes are
     * dominated by CR + LF line framing.
     *
     *   xflg active      -> xy_step (rare; state-machine receiving
     *                       coord bytes for cursor positioning)
     *   c >= 0x20        -> printable hot path (2 tests in, 1 cp +
     *                       1 jr c; everything else falls through)
     *   c == '\r'        -> CR (3 tests in)
     *   c == '\n'        -> LF treated as CR+LF (4 tests in)
     *   otherwise        -> specc(c) dispatch for the long tail of
     *                       0x00..0x1F controls (5 tests in)
     *
     * Previous order tested LF then CR before the printable path,
     * which cost 5 tests on every printable byte.  The new order
     * cuts printable to 2 tests (~14 T faster per char) while
     * keeping CR/LF cost unchanged. */
    if (xflg) {
        xy_step(c);
    } else if (c >= 0x20) {
        /* outcon[128] at 0xF680: output conversion table.  Only
         * looked up when prom1_only_sentinel == 0x5A and c < 0x80.
         * On two-PROM (sentinel == 0) the lookup is skipped entirely
         * (pass-through), so we never read from 0xF680 there (where
         * the data is stack workspace, not a locale table). */
        if (prom1_only_sentinel == 0x5A && !(c & 0x80)) {
            c = ((const uint8_t *)0xF680)[c];
        }
        *CELL(curx, cury) = c;
        cursor_right();
    } else if (c == '\r') {
        /* CR placed first among the control branches: most CP/M streams
         * emit CR+LF, and CR alone is also used for line overwrite. */
        curx = 0;
    } else if (c == '\n') {
        /* Treat LF as CR+LF for compatibility with code that emits bare
         * LFs (CCP and the netboot status line do this).  rcbios's specc
         * keeps LF as cursor-down only, but rcbios's CCP path differs. */
        cursor_down();
        curx = 0;
    } else {
        specc(c);
    }
    /* Defer 8275 cursor register update to _isr_crt (next VRTC): reduces
     * visible cursor flicker under fast streams and saves ~40 T per
     * character on the hot path.  The ISR reads curx/cury and clears
     * cur_dirty atomically wrt the mainline's single-store pattern. */
    cur_dirty = 1;
}

/* --- CP/M BIOS ABI shims ------------------------------------------ *
 *
 * Bridge between CP/M BIOS register convention and clang sdcccall(1):
 *
 *   CP/M:    CONST/CONIN no args, byte return in A.
 *            CONOUT/LIST char arg in C.
 *            BC and DE must survive across the call (CCP/NDOS use
 *            them as loop counters; HL clobber tolerated).
 *   clang:   First 8-bit arg in A.  8-bit return in A.  No callee-save.
 *
 * Each shim saves BC/DE, translates C->A where needed, calls impl_*,
 * restores BC/DE, returns.  7 bytes, ~50 T-states.  Console traffic
 * isn't hot-path so the call+pop+ret cost is acceptable.
 *
 * Phase 3 (2026-04-26): replaced bios_shims.s.  Naked C keeps the
 * register-translation logic next to the impl bodies it wraps; if an
 * impl ever changes its return convention, both halves are visible
 * in one diff.
 * ------------------------------------------------------------------ */

/* BIOS-JT trace logging (issue #60 diagnosis, 2026-05-08).
 *
 * Each instrumented shim writes one byte to __bios_log_buf at every
 * entry and exit:
 *    entry: slot | 0x10
 *    exit : slot | 0x20
 * Slot IDs: 2 = CONST, 3 = CONIN, 4 = CONOUT.  Buffer is 219 B in
 * unused IVT padding (sdcc/sections.asm); when full, logging stops
 * (no wrap, so earliest calls survive).  Buffer + idx live in
 * bss_ivt which the relocator zeroes pre-NDOS; we start at idx=0
 * with all bytes 0x00.
 *
 * Inline asm is gated on `MIRROR_SIOB && defined(__SDCC)` so clang's
 * original 6-instruction shims are unaffected.  Each block preserves
 * AF (incl. flags), BC, HL so the shim's pre/post register state is
 * unchanged from NDOS's POV.  Labels are globally unique because
 * z88dk-z80asm requires it (no local `1:`/`1f` syntax in this
 * dialect).
 */

/* BIOS-JT shims: original 6-instruction form.  Earlier
 * bug-#60-diagnostic instrumentation was removed once empirical
 * trace showed NDOS never reaches BIOS-JT calls under bug #2 (slave
 * crashes during NDOS COLDST's BIOS-JT walk, before CCP starts).
 * Frees ~70 B for SNIOS-side instrumentation which is the right
 * diagnosis layer. */

USED void bios_const_shim(void) __naked {
    ASM_VOLATILE(
        "push bc\n\t"
        "push de\n\t"
        "call _impl_const\n\t"
        "pop  de\n\t"
        "pop  bc\n\t"
        "ret\n\t"
    );
}

USED void bios_conin_shim(void) __naked {
    ASM_VOLATILE(
        "push bc\n\t"
        "push de\n\t"
        "call _impl_conin\n\t"
        "pop  de\n\t"
        "pop  bc\n\t"
        "ret\n\t"
    );
}

USED void bios_conout_shim(void) __naked {
    ASM_VOLATILE(
        "push bc\n\t"
        "push de\n\t"
        "ld   a, c\n\t"           /* CP/M: char in C -> clang: char in A */
        "call _impl_conout\n\t"
        "pop  de\n\t"
        "pop  bc\n\t"
        "ret\n\t"
    );
}

/* Payload integrity checksum placeholder (folded in from
 * payload_checksum.c, Phase 60).  Reserves the last 2 bytes of
 * .payload (see payload.ld).  Link-time value 0xFFFF;
 * cpnos-build/patch_payload_checksum.py overwrites it post-link with
 * the 16-bit additive sum of the preceding payload bytes.  At runtime
 * the relocator (relocator.c) recomputes the sum after copying and
 * compares — mismatch -> LDIR "BAD CHECKSUM" to display memory and
 * halt.  Catches missing prom1.ic65, bit-rot, mismatched PROM versions. */
SECTION_PAYLOAD_CKSUM
static const uint16_t payload_checksum_placeholder = 0xFFFF;
