; cpnos-rom z88dk section layout for SDCC build (Option C+).
;
; Single contiguous resident image at VMA 0xED00..0xF7FF (2.75 KB),
; physically split across PROM0 tail (0x0400..0x07FF, 1 KB) and
; PROM1 (0x2000..0x26FF, 1.75 KB).  prom_loader copies both chunks
; to RAM at boot.
;
; 2026-05-08: lowered from 0xEE00 to 0xED00 (+256 B) by shifting
; cpnos.com down 256 B (cpnos-build CODE_BASE LDE80 -> LDD80) and
; matching NIOS=0xED33 in cpnios-shim.asm.  Resident grew from
; 2560 B to 2816 B; TPA shrunk from ~54 KB to ~53 KB.
;
; Layout pinned by clang's payload.ld (we mirror it for source/ABI
; compatibility):
;
;   0xED00  RESIDENT_JUMPTABLE  _bios_boot — CP/M BIOS jump table base
;   0xED33  RESIDENT_SNIOS_JT   _snios_jt — DRI SNIOS jt (NDOS ABI)
;   ...     RESIDENT_SNIOS      SNIOS body, ISRs, all other code
;   ...     __ivt_start          IVT (Z80 IM2 vector table, 36 B; in BSS)
;   0xF800  display memory       hardware-mapped CRT video RAM
;
; Cold-init BSS at 0xEA00..0xECFF lives in the RAM region between
; cpnos.com tail (now 0xE9FF post-Path-6) and resident base (0xED00).
;
; PROM disable (OUT 0x18,A) does NOT happen in PROM0 — it lives in
; resident_handoff (cpnos_main.c) which runs from RAM after netboot.
;
; Linker-defined constants — clang's payload.ld supplies these via
; `--defsym` / linker-script assignment.  SDCC needs them as PUBLIC
; numeric constants so cross-TU references resolve.

    ; __ivt_start / __ivt_end are now defined as labels inside
    ; SECTION bss_ivt at the head of SCRATCH_BSS (page-aligned by
    ; SCRATCH_BSS's `org 0xEB00`).  The IVT pair is appended to the
    ; payload header's bss_pairs list (gen_payload_header.py
    ; --include-ivt) so the relocator zeroes the region before
    ; checksum verification.  See bottom of this file.

    ; _pio_rx_buf_page is derived from HIGH(_pio_rx_buf) AFTER the BSS
    ; chain is laid out — see SECTION bss_pio_rx near the bottom of
    ; this file.  The previous design declared it here as a hardcoded
    ; literal (0xF7) which silently disagreed with where SDCC actually
    ; placed `pio_rx_buf` (0xECEE in bss_compiler), so the ISR's
    ; `ld h, _pio_rx_buf_page; ld l, head` trick built addresses into
    ; resident code instead of into the buffer.  Deriving from HIGH()
    ; of the symbol's actual placement makes the constant impossible
    ; to drift from the buffer location — the linker computes both.

;-----------------------------------------------------------------
; PROM0 — reset vector + tiny prom_loader (lives at 0x0000..)
;-----------------------------------------------------------------

    SECTION RESET
    org 0x0000

    SECTION INIT_CODE
    SECTION INIT_RODATA

    ; PAYLOAD_HEADER -- generated by tasks/scripts/gen_payload_header.py
    ; into payload_header_data.s.  Lives between the relocator code
    ; (INIT_CODE) and chunk A (PROM0 0x0400, populated post-link by
    ; build_prom_image.py).  z88dk packs PAYLOAD_HEADER into the same
    ; anchor group as RESET/INIT_CODE/INIT_RODATA so all four show up
    ; in cpnos_RESET.bin and land at PROM0 offset 0 in the final image.
    SECTION PAYLOAD_HEADER

;-----------------------------------------------------------------
; RESIDENT — single contiguous block at 0xED00..0xF7FF (~2.75 KB).
;
; cpnos.com (cpnos-build) hardcodes NIOS = 0xED33 in cpnios-shim.asm.
; That requires _snios_jt at exactly 0xED33, which means _bios_boot
; at 0xED00 (BIOS jt is 51 bytes; SNIOS jt starts immediately after
; at 0xED00+51 = 0xED33).  Mirrors clang's _bios_boot=0xED00 layout.
;
; Section ordering (BIOS_JT first, then SNIOS, then everything else)
; matches clang's payload.ld so the resident image is structurally
; identical between the two builds.  Makefile dd-splits the resulting
; single per-section binary into PROM0 tail (first 1024 B → RAM
; 0xED00..0xF0FF) and PROM1 (next ≤1792 B → RAM 0xF100..0xF7FF;
; loader caps at 1792 to clear display memory at 0xF800).
;-----------------------------------------------------------------

    ; PAYLOAD_HEADER_P1 — duplicate of PAYLOAD_HEADER pinned at PROM1
    ; byte 0 (LMA 0x2000).  Same bytes as PAYLOAD_HEADER in PROM0; the
    ; relocator memcmps them at boot to detect cross-PROM mismatch
    ; (PROM0 from build N-1 + PROM1 from build N — the bug class that
    ; previously surfaced as "BAD CHECKSUM" with no operator hint of
    ; which PROMs were involved).  Anchored with `org 0x2000` so z88dk
    ; emits a separate per-section .bin (cpnos_PAYLOAD_HEADER_P1.bin)
    ; that the Makefile prepends to PROM1 ahead of resident chunk B.
    ; #62.
    SECTION PAYLOAD_HEADER_P1
    org 0x2000

    SECTION RESIDENT_JUMPTABLE
    org 0xED00

    SECTION RESIDENT_SNIOS_JT
    SECTION RESIDENT_SNIOS
    SECTION RESIDENT_ISR
    SECTION RESIDENT_PRE_CODE
    SECTION RESIDENT_PRE_RODATA
    SECTION RESIDENT_CODE

    ; --- z88dk runtime sections, pinned INSIDE the resident chain ---
    ;
    ; If we don't declare these, z88dk auto-places them in the next
    ; section chain it sees — which is SCRATCH_BSS at 0xEC00.  Any
    ; library function brought in there (`_memset`, `_memcpy`,
    ; `_memmove`, sccz80 helpers, etc.) lands in unloaded RAM, and
    ; calls jump into uninitialised memory.  By declaring the chain
    ; here we force them into the RAM that prom_loader actually
    ; copies (0xEE00..0xF7FF).  The check_sdcc_layout.py audit at
    ; build time enforces this invariant.
    SECTION code_clib
    SECTION code_crt_init
    SECTION code_home
    SECTION code_l_sccz80
    SECTION code_string
    SECTION code_compiler

    SECTION RESIDENT_RODATA

    ; Runtime RODATA / DATA aliases — same rationale as code_*: any
    ; library function that emits a literal string or table must
    ; resolve into PROM-loaded RAM.
    SECTION rodata_clib
    SECTION rodata_compiler
    SECTION rodata_string
    SECTION data_clib
    SECTION data_compiler

    SECTION RESIDENT_DATA

    ; Payload checksum placeholder — last 2 bytes of the resident.
    ; cpnos-build/patch_payload_checksum.py overwrites these bytes
    ; post-link so the 16-bit word-additive sum of the entire resident
    ; equals 0xCAFE.  Mirrors clang's payload_checksum.c (a 2-byte
    ; uint16_t placeholder in .payload_checksum, pinned at the end of
    ; .payload by payload.ld).
    ;
    ; This section MUST be the last non-zero-size section in the
    ; resident chain.  Declared in sections.asm rather than a separate
    ; .c file because the SDCC build doesn't have a per-symbol section
    ; attribute -- declaring here pins it via the section-ordering in
    ; this file.  Without this dedicated 2-byte slot, the checksum
    ; patcher overwrites whatever happens to be the last 2 bytes of
    ; the linked resident -- which becomes zp_init_data[6..7] when the
    ; resident shrinks below a threshold (root cause of #72).
    SECTION RESIDENT_CHECKSUM
    ; Force even alignment so the resident image's total size is even.
    ; patch_payload_checksum.py requires even-length input (it does
    ; word-additive arithmetic), and the relocator's runtime checksum
    ; verification reads the same word boundaries.  Without this, an
    ; odd-sized resident triggered a Makefile shell-pad workaround
    ; (#59).  align inserts 0 or 1 fill bytes BEFORE the defw, never
    ; touching the last 2 bytes the patcher overwrites.
    align 2
    PUBLIC __payload_checksum
__payload_checksum:
    defw 0xFFFF                    ; will be overwritten post-link

;-----------------------------------------------------------------
; SCRATCH BSS — VMA 0x0800 (NOLOAD; not in either PROM image).
;
; Clang puts BSS at 0xF524 (a 220 B gap between IVT at 0xF500 and
; pio_rx_buf at 0xF700).  SDCC's BSS is ~500 B and doesn't fit there.
; Putting it at 0xEC00 (the original cpnos_rom.ld scratch region)
; doesn't work either — that overlaps cpnos.com's load region
; (0xE180..0xEE00), and netboot's LDIR clobbers _cfgtbl mid-stream
; once cpnos.com fills past byte 0xA80 (sector 22).  Symptom: SNIOS
; netboot stalls at 22/25 dots because _cfgtbl.netst.ACTIVE gets
; overwritten and SNDMSG returns SNDERR on the next call.
;
; 0x0800..0x0BFF is ideal: RAM at boot (PROM0 only shadows
; 0x0000..0x07FF), unused during cold init, eventually becomes part
; of the user TPA (0x0100..0xCFFF) — by which point the BSS is dead
; (cold-init complete, cpnos.com handed control to NDOS).
;-----------------------------------------------------------------

    SECTION SCRATCH_BSS
    org 0xEA00            ; 2026-05-08 (Path 6): bumped 256 B further
                          ; from 0xEB00 in lockstep with cpnos-build
                          ; CODE_BASE shift LDE80 -> LDD80 (TPA ~54 KB ->
                          ; ~53 KB).  Resident extends down to 0xED00
                          ; absorbing the freed 256 B above bss_compiler.
                          ; bss_ivt at 0xEA00 (page-aligned), bss_pio_rx
                          ; at 0xEB00 (next page), bss_compiler at 0xEC00.

    ; IM2 IVT — 36 B (18 entries × 2 B) at the head of the page so
    ; dev_byte = 0..0x22 indexes correctly off `I = 0xEA`.  Page-aligned
    ; by SCRATCH_BSS's `org 0xEA00` (no extra `align` needed).  The
    ; payload header carries (__ivt_start, __ivt_end) in its bss_pairs
    ; list (Makefile passes `--include-ivt` to gen_payload_header) so
    ; the relocator zeroes this region before checksum verification.
    SECTION bss_ivt
    PUBLIC __ivt_start
    PUBLIC __ivt_end
__ivt_start:
    defs 36
__ivt_end:

    ; (bios_log_buf / bios_log_idx removed in #72 -- issue #60 closed,
    ; bios_log_byte helper in resident.c also removed.  220 B of IVT-
    ; page padding now unused.)

    ; PIO-B receive ring — page-aligned 256-byte buffer at 0xEB00.
    ; Defined here (not in transport_pio.c) so the linker places it at
    ; a page boundary AND so _pio_rx_buf_page can be derived from
    ; HIGH(_pio_rx_buf) instead of being a hardcoded literal that can
    ; drift from the actual placement.  ISR reads via `ld h,
    ; _pio_rx_buf_page; ld l, head` so the buffer MUST be page-aligned.
    SECTION bss_pio_rx
    align 256
    PUBLIC _pio_rx_buf
_pio_rx_buf:
    defs 256

    PUBLIC _pio_rx_buf_page
    defc _pio_rx_buf_page = _pio_rx_buf / 256

    SECTION bss_compiler

    ; BSS aliases the z88dk libs may emit.  These need to be in the
    ; BSS scratch range (zeroed on cold init), not in unrelated RAM.
    SECTION bss_clib
    SECTION bss_string

;-----------------------------------------------------------------
; Linker symbols read by the payload header (payload_header_data.s).
;
; SCRATCH_BSS itself is empty (size 0); the actual BSS bytes live
; in its sub-sections.  Span the whole chain by using the head of
; the first sub-section (bss_pio_rx, page-aligned at 0xEB00) and
; the tail of the last (bss_string).
;
; chunk_a_size is fixed at 736 to match build_prom_image.py's dd-split
; at PROM0 0x0520 (was 1024 / 0x0400 pre-Phase-51A.2; Phase 51A.2 moved
; chunk A start to 0x0520 to mirror clang's layout, giving INIT_CODE
; the room to absorb cpnos_cold.c).  chunk_b_size is derived from
; where RESIDENT_CHECKSUM actually ends (RESIDENT_CHECKSUM is the LAST
; section in the resident chain, holding the 2-byte slot the post-link
; checksum patcher writes to), so growing the resident grows chunk_b
; automatically (no Makefile edit).  Using RESIDENT_CHECKSUM_tail
; (not RESIDENT_DATA_tail) so the chunk includes the checksum bytes.
;-----------------------------------------------------------------

    EXTERN __bss_pio_rx_head
    EXTERN __bss_string_tail
    EXTERN __RESIDENT_CHECKSUM_tail

    PUBLIC __scratch_bss_start
    PUBLIC __scratch_bss_end
    defc __scratch_bss_start = __bss_pio_rx_head
    defc __scratch_bss_end   = __bss_string_tail

    PUBLIC __pio_rx_bss_start
    PUBLIC __pio_rx_bss_end
    defc __pio_rx_bss_start = _pio_rx_buf
    defc __pio_rx_bss_end   = _pio_rx_buf + 256

    PUBLIC __payload_chunk_a_size
    PUBLIC __payload_chunk_b_size
    defc __payload_chunk_a_size = 736
    defc __payload_chunk_b_size = __RESIDENT_CHECKSUM_tail - 0xED00 - 736
