; Generated by Makefile from TRANSPORT=pio-irq.
    SECTION RESIDENT_CODE
    PUBLIC _xport_send_byte
    EXTERN _transport_pio_send_byte
_xport_send_byte:
    jp _transport_pio_send_byte
    PUBLIC _xport_recv_byte
    EXTERN _transport_pio_recv_byte
_xport_recv_byte:
    jp _transport_pio_recv_byte
