#!/usr/bin/env python3
"""Generate a QR code as ROA327 sextant character codes for the RC700 PROM.

Tight 2x3 packing: each screen character cell is one ROA327 sextant glyph
covering 2 QR modules horizontally x 3 vertically.  A version-2 (25x25) code
therefore fits in ceil(25/2) x ceil(25/3) = 13 x 9 = 117 cells.

The RC702 8275 shows 11 dot-lines per character (init_crt crt_param(0x9A)), so
all three sextant zones (top lines 0-2, mid 3-6, bot 7-10) are visible -- the
full 6-bit block renders.  Do NOT scale the modules; scaling wastes cells.

No quiet zone is baked into the data: the draw routine places the block in a
field of blanks, which supplies the quiet border, and brackets it with 8275
field attributes (0x84 = GPA0=1 -> select ROA327/SEM702; 0x80 = back to
ROA296) so the sextant codes are looked up in ROA327 rather than the main font.
"""

import qrcode

URL = "github.com/ravn/rc700-gensmedet"
OUTPUT = "clang/qr_data.h"


def pattern_to_charcode(pattern):
    """6-bit sextant pattern (bit0=top-left ... bit5=bot-right) -> ROA327 code."""
    return 0x20 + pattern if pattern < 32 else 0x60 + (pattern - 32)


def main():
    # mask_pattern=3 chosen empirically: of the 8 valid masks it ZX0-compresses
    # smallest as sextant cells (108 vs 110 B) -- still a spec-valid QR.
    qr = qrcode.QRCode(version=2,
                       error_correction=qrcode.constants.ERROR_CORRECT_L,
                       box_size=1, border=0, mask_pattern=3)
    qr.add_data(URL)
    qr.make(fit=False)
    m = qr.modules
    n = len(m)
    assert n == 25, f"expected 25x25, got {n}x{n}"

    def px(y, x):
        return 1 if (0 <= y < n and 0 <= x < n and m[y][x]) else 0

    cols = (n + 1) // 2   # 13
    rows = (n + 2) // 3   # 9
    screen = []
    for br in range(rows):
        for bc in range(cols):
            y0, x0 = br * 3, bc * 2
            pat = (px(y0, x0)          | (px(y0, x0 + 1) << 1) |
                   (px(y0 + 1, x0) << 2) | (px(y0 + 1, x0 + 1) << 3) |
                   (px(y0 + 2, x0) << 4) | (px(y0 + 2, x0 + 1) << 5))
            screen.append(pattern_to_charcode(pat))

    with open(OUTPUT, "w") as f:
        f.write(f"/* QR code (ROA327 sextants) for: {URL}\n")
        f.write(f" * Version 2, EC L, {n}x{n} modules -> tight 2x3 = {cols}x{rows}"
                f" = {len(screen)} cells.\n")
        f.write(" * Generated by gen_qr.py -- do not edit.  Render with GPA0=1"
                " (field attr 0x84). */\n\n")
        f.write(f"#define QR_COLS {cols}\n")
        f.write(f"#define QR_ROWS {rows}\n\n")
        f.write(f"static const byte qr_screen[{len(screen)}] = {{\n")
        for r in range(rows):
            row = screen[r * cols:(r + 1) * cols]
            f.write("    " + "".join(f"0x{b:02x}," for b in row) + "\n")
        f.write("};\n")

    print(f"Generated {OUTPUT}: {cols}x{rows} = {len(screen)} cells, URL={URL}")
    print()
    for row in m:
        print("".join("##" if c else "  " for c in row))


if __name__ == "__main__":
    main()
