; ZX0-compressed payload.bin (resident at VMA 0xED00, unchanged from
; the existing build).  Generated by the prom1-lineprog Makefile target.
	.section .payload_zx0,"a",@progbits
	.incbin "clang-prom1lineprog/payload.zx0"
