#!/usr/bin/env python3
"""Audit cpnos.map (z88dk-z80asm output) for symbols that the build will
silently misroute at runtime.

z88dk inserts standard-library sections (`code_string`, `code_clib`,
`code_l_sccz80`, `code_home`, `code_crt_init`) into address gaps when
they are not explicitly placed.  In the cpnos-rom layout that puts them
in the SCRATCH_BSS chain at 0xEDF1+, which is OUTSIDE the resident
range (0xED00..0xF7FF) that the relocator copies to RAM.  Calls to
those symbols at runtime hit uninitialised RAM.

Detect this by checking every `addr, public` symbol falls inside one of
the legal ranges:

    0x0000..0x07FF  PROM0 (RESET, INIT_CODE, INIT_RODATA, PAYLOAD_HEADER)
    0xEC00..0xEDFF  bss_compiler ONLY (zero-initialised at boot)
    0xED00..0xF7FF  resident (LDIRed by the relocator)

A symbol in a `code_*` or `RESIDENT_*` or `SECTION` flagged section
must live in 0x0000..0x07FF (init/reset code) or 0xED00..0xF7FF
(resident).  A symbol in `bss_compiler` is allowed in 0xEC00..0xEDFF.

Also flag any section whose head/tail straddles the resident boundary
at 0xED00 (overlaps with RESIDENT_JUMPTABLE).

Payload-header sanity: the header is generated by gen_payload_header.py
and ends up in the PAYLOAD_HEADER section of the SDCC link.  The audit
verifies the magic (0x6350) and a sentinel pair (0xFFFF, 0xFFFF) at
the right place in cpnos_RESET.bin -- catches a stale generator script
or a missed symbol-resolution failure that leaves the header zeroed
or partial.  Pass cpnos_RESET.bin as the second positional argument
(optional; if omitted the header sanity check is skipped).

Exit non-zero if violations are found.
"""
import re
import sys
from pathlib import Path

RESIDENT_LO = 0xED00
RESIDENT_HI = 0xF7FF      # inclusive
PROM0_LO = 0x0000
PROM0_HI = 0x07FF
# PROM1 is mapped at LMA 0x2000..0x27FF.  Hosts PAYLOAD_HEADER_P1 (the
# duplicate header for cross-PROM mismatch detection, #62) at byte 0;
# resident chunk B follows.  Chunk B is part of the resident chain
# (anchored at 0xED00 VMA) and gets its LMA from the dd-split, NOT from
# z88dk -- so chunk B never appears as a separate section in cpnos.map.
PROM1_LO = 0x2000
PROM1_HI = 0x27FF
# BSS scratch range: extended down to 0xEA00 in lockstep with the
# 2026-05-08 cpnos-build CODE_BASE shift LDE80 -> LDD80 (Path 6), so
# the SDCC build can grow resident from 2560 B to 2816 B and host a
# page-aligned `bss_ivt` slot at 0xEA00.
BSS_LO = 0xEA00
BSS_HI = 0xECFF

# Sections that are allowed to live outside the resident range.
BSS_SECTIONS = {"bss_compiler", "SCRATCH_BSS"}
PROM0_SECTIONS = {"RESET", "INIT_CODE", "INIT_RODATA", "PAYLOAD_HEADER"}
PROM1_SECTIONS = {"PAYLOAD_HEADER_P1"}

# Const/equ symbols (no real address, just a numeric definition).
def is_const(line: str) -> bool:
    return ", const," in line


def addr_in(addr: int, lo: int, hi: int) -> bool:
    return lo <= addr <= hi


# Match cpnos-rom/payload_header.h
PAYLOAD_HEADER_MAGIC = 0x6350
PAYLOAD_HEADER_VERSION = 0x0001
PAYLOAD_BSS_SENTINEL = 0xFFFF


def check_payload_header(map_path: Path,
                         reset_bin: Path,
                         violations: list,
                         warnings: list) -> None:
    """Read the PAYLOAD_HEADER bytes out of cpnos_RESET.bin and
    verify magic / version / sentinel terminator.

    Catches three failure modes:
    - gen_payload_header.py wasn't invoked or produced an empty file
      (header bytes are 0x00 or 0xFF).
    - A symbol in the header (e.g., __RESIDENT_DATA_tail) failed to
      resolve at link time and the linker silently substituted 0.
    - The bss_pairs list grew past what the relocator expects without
      a sentinel terminator -- relocator would loop forever.
    """
    # Find _payload_header offset within cpnos_RESET.bin.  cpnos_RESET.bin
    # starts at PROM0 0x0000, so _payload_header's address IS the offset.
    header_addr = None
    pat = re.compile(r"^_payload_header\s*=\s*\$([0-9A-Fa-f]+)\s*;")
    for line in map_path.read_text().splitlines():
        m = pat.match(line)
        if m:
            header_addr = int(m.group(1), 16)
            break
    if header_addr is None:
        violations.append("_payload_header symbol missing from cpnos.map "
                          "-- gen_payload_header.py output not linked?")
        return

    if not reset_bin.exists():
        warnings.append(f"cpnos_RESET.bin not found at {reset_bin}; "
                        f"skipping payload-header byte verification")
        return

    data = reset_bin.read_bytes()
    if header_addr + 4 > len(data):
        violations.append(
            f"_payload_header at offset 0x{header_addr:04X} but "
            f"cpnos_RESET.bin is only {len(data)} B")
        return

    magic = data[header_addr] | (data[header_addr + 1] << 8)
    version = data[header_addr + 2] | (data[header_addr + 3] << 8)

    if magic != PAYLOAD_HEADER_MAGIC:
        violations.append(
            f"payload-header magic mismatch: cpnos_RESET.bin@0x{header_addr:04X} "
            f"= 0x{magic:04X}, expected 0x{PAYLOAD_HEADER_MAGIC:04X} "
            f"-- header generator did not run, or its output got "
            f"clobbered by another section")
        return

    if version != PAYLOAD_HEADER_VERSION:
        violations.append(
            f"payload-header version mismatch: 0x{version:04X}, "
            f"expected 0x{PAYLOAD_HEADER_VERSION:04X} -- relocator "
            f"and generator disagree on header layout")
        return

    # Walk the header looking for a sentinel pair.  Header layout is
    # 9 fixed fields × 2 B = 18 B, then bss_pairs[][2] terminated by
    # (PAYLOAD_BSS_SENTINEL, anything).  Sanity check: sentinel must
    # appear within the next 64 B (room for ~20 BSS pairs).
    bss_off = header_addr + 18
    found_sentinel = False
    while bss_off < header_addr + 18 + 64 and bss_off + 4 <= len(data):
        start = data[bss_off] | (data[bss_off + 1] << 8)
        if start == PAYLOAD_BSS_SENTINEL:
            found_sentinel = True
            break
        bss_off += 4
    if not found_sentinel:
        violations.append(
            f"payload-header bss_pairs list missing sentinel "
            f"(0x{PAYLOAD_BSS_SENTINEL:04X}) within 64 B after header -- "
            f"relocator's BSS-clear loop will run off the end")


def parse_map(path: Path):
    """Yield (name, addr, kind, scope, defined, section, source_loc)."""
    rx = re.compile(
        r"^(\S+)\s*=\s*\$([0-9A-Fa-f]+)\s*;\s*"
        r"(addr|const)\s*,\s*(\S+?)\s*,\s*(\S*?)\s*,\s*(\S*?)\s*,\s*(\S*?)\s*,\s*(.*)$"
    )
    for line in path.read_text().splitlines():
        m = rx.match(line)
        if not m:
            continue
        name, addr_hex, kind, scope, defined, module, section, src = m.groups()
        yield {
            "name": name,
            "addr": int(addr_hex, 16),
            "kind": kind,
            "scope": scope,
            "defined": defined,
            "module": module,
            "section": section,
            "src": src,
            "raw": line,
        }


def parse_section_extents(path: Path):
    """Pick out __FOO_head / __FOO_size / __FOO_tail synthesised by z80asm
    and return {section_name: (head, size, tail)}."""
    rx = re.compile(
        r"^__(\S+?)_(head|size|tail)\s*=\s*\$([0-9A-Fa-f]+)\s*;"
    )
    sec = {}
    for line in path.read_text().splitlines():
        m = rx.match(line)
        if not m:
            continue
        name, kind, hex_v = m.groups()
        sec.setdefault(name, {})[kind] = int(hex_v, 16)
    return {n: (d.get("head"), d.get("size"), d.get("tail")) for n, d in sec.items()}


def main(map_path, reset_bin_path=None):
    p = Path(map_path)
    if not p.exists():
        print(f"check_sdcc_layout: missing map {p}", file=sys.stderr)
        return 1

    violations = []
    warnings = []

    # --- Payload-header sanity ----------------------------------------------
    # Look for cpnos_RESET.bin alongside cpnos.map by default.
    if reset_bin_path is None:
        reset_bin_path = str(p.with_name("cpnos_RESET.bin"))
    check_payload_header(p, Path(reset_bin_path), violations, warnings)

    # --- Section-extent audit -------------------------------------------------
    sections = parse_section_extents(p)
    for name, (head, size, tail) in sorted(sections.items()):
        if head is None or tail is None:
            continue
        if size == 0:
            continue
        # Sections we control directly
        if name in PROM0_SECTIONS:
            if not (addr_in(head, PROM0_LO, PROM0_HI)
                    and addr_in(tail - 1, PROM0_LO, PROM0_HI)):
                violations.append(
                    f"section {name} ({head:04X}..{tail-1:04X}) "
                    f"outside PROM0 range")
            continue
        if name in PROM1_SECTIONS:
            if not (addr_in(head, PROM1_LO, PROM1_HI)
                    and addr_in(tail - 1, PROM1_LO, PROM1_HI)):
                violations.append(
                    f"section {name} ({head:04X}..{tail-1:04X}) "
                    f"outside PROM1 range {PROM1_LO:04X}..{PROM1_HI:04X}")
            continue
        if name in BSS_SECTIONS:
            if not (addr_in(head, BSS_LO, BSS_HI + 1)
                    and addr_in(tail, BSS_LO, BSS_HI + 1)):
                violations.append(
                    f"section {name} ({head:04X}..{tail:04X}) "
                    f"outside BSS range")
            continue
        if name.startswith("RESIDENT_"):
            if not (addr_in(head, RESIDENT_LO, RESIDENT_HI + 1)
                    and addr_in(tail, RESIDENT_LO, RESIDENT_HI + 1)):
                violations.append(
                    f"section {name} ({head:04X}..{tail:04X}) "
                    f"outside resident range "
                    f"{RESIDENT_LO:04X}..{RESIDENT_HI:04X}")
            continue
        # Compiler runtime CODE sections — these MUST live inside the
        # resident range for their symbols to be reachable from RAM.
        if name.startswith("code_"):
            if not (addr_in(head, RESIDENT_LO, RESIDENT_HI + 1)
                    and addr_in(tail, RESIDENT_LO, RESIDENT_HI + 1)):
                violations.append(
                    f"runtime section {name} ({head:04X}..{tail:04X}) "
                    f"placed OUTSIDE resident range — symbols there are "
                    f"NOT loaded into RAM by the relocator; calls will jump "
                    f"into uninitialised memory")
            continue
        # Compiler runtime RODATA / DATA — also need to be loaded.
        if name.startswith("rodata_") or name.startswith("data_"):
            if not (addr_in(head, RESIDENT_LO, RESIDENT_HI + 1)
                    and addr_in(tail, RESIDENT_LO, RESIDENT_HI + 1)):
                violations.append(
                    f"runtime section {name} ({head:04X}..{tail:04X}) "
                    f"placed OUTSIDE resident range — read-only / data "
                    f"there is NOT loaded into RAM, reads will return "
                    f"uninitialised values")
            continue
        # Compiler runtime BSS — must live inside BSS scratch range
        # (zeroed at boot).  Outside that range, initial values are
        # whatever the netboot LDIR happened to leave behind.
        if name.startswith("bss_"):
            if not (addr_in(head, BSS_LO, BSS_HI + 1)
                    and addr_in(tail, BSS_LO, BSS_HI + 1)):
                violations.append(
                    f"runtime section {name} ({head:04X}..{tail:04X}) "
                    f"placed OUTSIDE bss range {BSS_LO:04X}..{BSS_HI:04X} "
                    f"— variables there start with garbage, not zero")
            continue
        # Any other section (IGNORE etc.) — warn only
        warnings.append(
            f"unhandled section {name} ({head:04X}..{tail:04X})")

    # --- Per-symbol audit -----------------------------------------------------
    for s in parse_map(p):
        if s["kind"] != "addr":
            continue
        addr = s["addr"]
        sect = s["section"]
        if not sect:
            # Linker-synthesised symbol (e.g., __FOO_head) — covered above.
            continue
        # Derived high-byte constants (e.g., `_pio_rx_buf_page = HIGH(_pio_rx_buf)`)
        # appear in the map with the section of their `defc` site but a value
        # < 0x100 because they're a single byte, not an address.  Skip them —
        # by convention these symbols end in `_page` or `_PAGE`.
        if s["name"].lower().endswith("_page") and addr < 0x100:
            continue
        # Allow PROM0 ranges for boot code only
        if sect in PROM0_SECTIONS:
            ok = addr_in(addr, PROM0_LO, PROM0_HI)
        elif sect in BSS_SECTIONS or sect.startswith("bss_"):
            ok = addr_in(addr, BSS_LO, BSS_HI)
        elif (sect.startswith("RESIDENT_")
              or sect.startswith("code_")
              or sect.startswith("rodata_")
              or sect.startswith("data_")):
            ok = addr_in(addr, RESIDENT_LO, RESIDENT_HI)
        else:
            # Unknown section — let it pass with a note
            ok = True
            warnings.append(
                f"symbol {s['name']:30s} @ {addr:04X} in unknown "
                f"section {sect!r}")
            continue
        if not ok:
            violations.append(
                f"symbol {s['name']:30s} @ {addr:04X} in section "
                f"{sect!r} — addr outside the legal range for that section "
                f"(defined {s['src']})")

    # --- Cross-section overlap check -----------------------------------------
    # Every byte at a given address should be claimed by at most one
    # *non-zero-size* section.  Catch the code_string vs RESIDENT_JUMPTABLE
    # collision.
    spans = []
    for name, (head, size, tail) in sections.items():
        if size and size > 0 and head is not None and tail is not None:
            # Tails are exclusive (head + size).
            if head < tail:
                spans.append((head, tail, name))
    spans.sort()
    for i in range(len(spans)):
        a_lo, a_hi, a_n = spans[i]
        for j in range(i + 1, len(spans)):
            b_lo, b_hi, b_n = spans[j]
            if b_lo >= a_hi:
                break
            if a_n == b_n:
                continue
            ov_lo = max(a_lo, b_lo)
            ov_hi = min(a_hi, b_hi)
            if ov_lo < ov_hi:
                violations.append(
                    f"section overlap: {a_n} ({a_lo:04X}..{a_hi-1:04X}) "
                    f"vs {b_n} ({b_lo:04X}..{b_hi-1:04X}) at "
                    f"{ov_lo:04X}..{ov_hi-1:04X}")

    # --- Report --------------------------------------------------------------
    if warnings:
        print("warnings:", file=sys.stderr)
        for w in warnings:
            print(f"  {w}", file=sys.stderr)
    if violations:
        print(f"check_sdcc_layout: {len(violations)} VIOLATION(S):",
              file=sys.stderr)
        for v in violations:
            print(f"  {v}", file=sys.stderr)
        return 2
    print("check_sdcc_layout: layout OK")
    return 0


if __name__ == "__main__":
    if len(sys.argv) not in (2, 3):
        print(f"usage: {sys.argv[0]} <cpnos.map> [<cpnos_RESET.bin>]",
              file=sys.stderr)
        sys.exit(1)
    sys.exit(main(*sys.argv[1:]))
