#!/usr/bin/env python3
"""Emit payload_header_data.s for the cpnos-rom relocator stage.

Reads symbols from the payload link (clang's payload.elf via llvm-nm, OR
SDCC's cpnos_payload.map directly) and emits an assembly file that
defines the `_payload_header` struct at PROM offset 0 of its containing
section.  Both relocator pipelines link this generated .s into the PROM
image so the relocator can read its metadata at boot — replacing the
old `--defsym` injection (clang) and `prom_loader.asm` hardcoded
literals (SDCC).

The header layout matches `cpnos-rom/payload_header.h`:
  +0  magic       0x6350
  +2  version     0x0001
  +4  resident_dest    = _bios_boot
  +6  chunk_a_src      = (linker-emitted later — see notes)
  +8  chunk_a_size     = (passed in via --chunk-a-size)
  +10 chunk_b_src      = (linker-emitted later)
  +12 chunk_b_size     = (computed from payload-size − chunk-a-size)
  +14 cold_entry       = _cpnos_cold_entry
  +16 checksum_magic   = 0xCAFE
  +18 bss_pairs[]      = pairs (start, end), terminated by (0xFFFF, 0xFFFF)

`chunk_a_src` and `chunk_b_src` are NOT resolved by this script — they
are the addresses where chunk A and chunk B *physically land* in the
relocator's PROM binary, which the relocator linker decides.  We emit
asm references like `defw __chunk_a_start` so the linker resolves them
when assembling the relocator image.  The symbols `__chunk_a_start`
and `__chunk_b_start` must be defined by the relocator linker script
(e.g. via `__chunk_a_start = .;` immediately before the chunk A INCBIN).

This separation matches the architectural invariant: the payload link
knows nothing about PROMs; PROM addresses are stage-2 concerns.

Usage:
    gen_payload_header.py --syntax=clang|sdcc \
                          --payload-elf=path/payload.elf | --map=path/cpnos_payload.map \
                          --payload-bin=path/payload.bin \
                          --chunk-a-size=N \
                          [--include-ivt] \
                          --out=path/payload_header_data.s
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


def read_symbols_from_elf(elf_path: str, llvm_nm: str) -> dict[str, int]:
    """Run llvm-nm on the payload ELF and return a {name: address} dict."""
    out = subprocess.check_output([llvm_nm, "--defined-only", elf_path],
                                  text=True)
    syms = {}
    for line in out.splitlines():
        # Format: "ADDR T name" where T is the symbol type letter.
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            addr = int(parts[0], 16)
        except ValueError:
            continue
        name = parts[2]
        syms[name] = addr
    return syms


def read_symbols_from_map(map_path: str) -> dict[str, int]:
    """Parse a z88dk-z80asm .map file and return a {name: address} dict.

    Map line format example:
        _bios_boot                      = $EE00 ; addr, public, , ...
    """
    syms = {}
    rx = re.compile(r"^(\S+)\s*=\s*\$([0-9A-Fa-f]+)\s*;\s*addr\s*,")
    for line in Path(map_path).read_text().splitlines():
        m = rx.match(line)
        if m:
            syms[m.group(1)] = int(m.group(2), 16)
    return syms


def _emit_clang_section(out, fields, section_name, symbol_name):
    out.write(f'.section {section_name},"a",@progbits\n')
    out.write(f".global {symbol_name}\n")
    out.write(f"{symbol_name}:\n")
    for name, value in fields:
        comment = f"  ; {name}" if name else ""
        if isinstance(value, str):
            out.write(f"    .short {value}{comment}\n")
        else:
            out.write(f"    .short {value:#06x}{comment}\n")


def fmt_clang(out, fields, emit_p1=True):
    """Emit GAS-Z80 dialect (clang).  When emit_p1, a duplicate
    header in .payload_header_p1 is appended for the cross-PROM
    mismatch check; relocator.ld anchors that section at PROM1
    byte 0."""
    out.write("; Generated by gen_payload_header.py — DO NOT EDIT.\n")
    out.write("; Header layout matches cpnos-rom/payload_header.h.\n\n")
    _emit_clang_section(out, fields,
                        ".payload_header", "_payload_header")
    if emit_p1:
        out.write("\n")
        _emit_clang_section(out, fields,
                            ".payload_header_p1", "_payload_header_p1")


def _emit_sdcc_section(out, fields, section_name, symbol_name):
    out.write(f"    SECTION {section_name}\n")
    out.write(f"    PUBLIC {symbol_name}\n")
    out.write(f"{symbol_name}:\n")
    for name, value in fields:
        comment = f"  ; {name}" if name else ""
        if isinstance(value, str):
            out.write(f"    defw {value}{comment}\n")
        else:
            out.write(f"    defw {value:#06x}{comment}\n")


def fmt_sdcc(out, fields, emit_p1=True):
    """Emit z88dk-z80asm dialect (SDCC).  When emit_p1, a duplicate
    header in PAYLOAD_HEADER_P1 is appended for the cross-PROM
    mismatch check; sdcc/sections.asm must anchor that section at
    PROM1 byte 0 (not yet wired -- see dual-header-plan-2026-05-08.md
    for the SDCC follow-up scope).  Pass --no-emit-p1-header for
    SDCC builds until that lands."""
    out.write("; Generated by gen_payload_header.py -- DO NOT EDIT.\n")
    out.write("; Header layout matches cpnos-rom/payload_header.h.\n\n")
    extern_syms = []
    for name, value in fields:
        if isinstance(value, str) and value not in extern_syms:
            extern_syms.append(value)
    for sym in extern_syms:
        out.write(f"    EXTERN {sym}\n")
    out.write("\n")
    _emit_sdcc_section(out, fields, "PAYLOAD_HEADER", "_payload_header")
    if emit_p1:
        out.write("\n")
        _emit_sdcc_section(out, fields,
                           "PAYLOAD_HEADER_P1", "_payload_header_p1")


# Magic / version / sentinel — must match cpnos-rom/payload_header.h.
MAGIC = 0x6350
VERSION = 0x0001
CHECKSUM_MAGIC = 0xCAFE
SENTINEL = 0xFFFF

BUILD_DATE_STR_LEN = 16  # matches char build_date_str[16] in struct


def build_date_fields(date_str: str):
    """Encode a 16-char date string as 8 little-endian word fields.
    Pads or truncates to BUILD_DATE_STR_LEN to keep the field size
    invariant -- the relocator reads exactly 16 bytes."""
    pad = (date_str + " " * BUILD_DATE_STR_LEN)[:BUILD_DATE_STR_LEN]
    out = []
    for i in range(0, BUILD_DATE_STR_LEN, 2):
        word = ord(pad[i]) | (ord(pad[i + 1]) << 8)
        out.append((f"build_date_w{i // 2}", word))
    return out


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--syntax", choices=("clang", "sdcc"), required=True)
    p.add_argument("--payload-elf", help="Path to payload.elf (clang)")
    p.add_argument("--map", help="Path to cpnos_payload.map (SDCC, optional "
                                 "in symbolic mode)")
    p.add_argument("--payload-bin",
                   help="Path to payload.bin (clang: used to derive "
                        "chunk_b_size; SDCC: ignored in symbolic mode)")
    p.add_argument("--chunk-a-size", type=int,
                   help="dd-split boundary in bytes (clang: required, "
                        "SDCC: optional -- if omitted, uses linker symbol)")
    p.add_argument("--chunk-a-src", type=lambda v: int(v, 0), default=None,
                   help="PROM LMA of chunk A (SDCC build constant, e.g. "
                        "0x0400).  Clang resolves via __chunk_a_start.")
    p.add_argument("--chunk-b-src", type=lambda v: int(v, 0), default=None,
                   help="PROM LMA of chunk B (SDCC build constant, e.g. "
                        "0x2000).  Clang resolves via __chunk_b_start.")
    p.add_argument("--llvm-nm", default="llvm-nm",
                   help="llvm-nm binary (clang only)")
    p.add_argument("--include-ivt", action="store_true",
                   help="Add (__ivt_start, __ivt_end) to bss_pairs")
    p.add_argument("--build-date-str", default="????-??-?? ??:??",
                   help="Build date stamp written into the header's "
                        "build_date_str[16] field, ASCII, 16 chars "
                        "(\"YYYY-MM-DD HH:MM\"). Read by the relocator "
                        "and copied to display memory at boot so the "
                        "operator can identify the build before any "
                        "resident code runs.")
    p.add_argument("--emit-p1-header", action=argparse.BooleanOptionalAction,
                   default=True,
                   help="Emit a duplicate header (.payload_header_p1 / "
                        "PAYLOAD_HEADER_P1) for the relocator to memcmp "
                        "against the PROM0 header at boot, catching "
                        "cross-PROM mismatch.  Clang's relocator.ld "
                        "anchors the dup at PROM1 byte 0; the SDCC "
                        "build's sections.asm needs equivalent anchoring "
                        "before this can be enabled there (tracked as "
                        "follow-up in tasks/dual-header-plan-2026-05-08.md). "
                        "Pass --no-emit-p1-header for the SDCC build.")
    p.add_argument("--symbolic", action="store_true",
                   help="Emit linker-symbol references instead of resolved "
                        "values (SDCC single-link mode -- header is part of "
                        "the same link as the resident, so the linker "
                        "resolves the symbols directly)")
    p.add_argument("--out", required=True)
    args = p.parse_args()

    if args.syntax == "clang":
        if not args.payload_elf:
            p.error("--payload-elf required for --syntax=clang")
        if args.chunk_a_size is None:
            p.error("--chunk-a-size required for --syntax=clang")
        if not args.payload_bin:
            p.error("--payload-bin required for --syntax=clang")
        syms = read_symbols_from_elf(args.payload_elf, args.llvm_nm)

        def sym(name):
            if name not in syms:
                sys.exit(f"missing symbol in payload link: {name}")
            return syms[name]

        payload_size = os.path.getsize(args.payload_bin)
        chunk_a_size = args.chunk_a_size
        chunk_b_size = payload_size - chunk_a_size
        if chunk_b_size < 0:
            sys.exit(f"chunk-a-size {chunk_a_size} exceeds payload-bin size {payload_size}")

        fields = [
            ("magic",          MAGIC),
            ("version",        VERSION),
            ("resident_dest",  sym("_bios_boot")),
            # Clang relocator.ld emits these symbols at the chunk LMAs.
            ("chunk_a_src",    "__chunk_a_start"),
            ("chunk_a_size",   chunk_a_size),
            ("chunk_b_src",    "__chunk_b_start"),
            ("chunk_b_size",   chunk_b_size),
            ("cold_entry",     sym("_cpnos_cold_entry")),
            ("checksum_magic", CHECKSUM_MAGIC),
        ]
        fields += build_date_fields(args.build_date_str)
        fields += [
            ("scratch_bss_start", sym("__scratch_bss_start")),
            ("scratch_bss_end",   sym("__scratch_bss_end")),
            ("pio_rx_bss_start",  sym("__pio_rx_bss_start")),
            ("pio_rx_bss_end",    sym("__pio_rx_bss_end")),
        ]
        if args.include_ivt:
            fields += [
                ("ivt_start", sym("__ivt_start")),
                ("ivt_end",   sym("__ivt_end")),
            ]
        fields += [
            ("sentinel", SENTINEL),
            ("sentinel", SENTINEL),
        ]
        with open(args.out, "w") as out:
            fmt_clang(out, fields, emit_p1=args.emit_p1_header)
        print(f"gen_payload_header: wrote {args.out} (clang, "
              f"chunk_a={chunk_a_size} chunk_b={chunk_b_size}, "
              f"payload_size={payload_size}, "
              f"build_date='{args.build_date_str}')")
        return 0

    # SDCC.  Two sub-modes:
    #
    #   --symbolic: emit `defw _symbol` references for everything
    #     resolvable by the linker.  Chunk LMAs and chunk_a_size come
    #     from CLI args (build-script constants); chunk_b_size is
    #     resolved via a defc symbol the linker-script computes from
    #     z88dk's __SECTION_*_head/tail.  No --map needed.
    #
    #   non-symbolic: read --map and resolve every symbol now.  Used
    #     when the SDCC build does a two-stage link (future work --
    #     not exercised by the current single-stage SDCC pipeline).
    if args.symbolic:
        if args.chunk_a_src is None or args.chunk_b_src is None:
            p.error("--chunk-a-src and --chunk-b-src required for "
                    "--syntax=sdcc --symbolic")
        chunk_a_size_field = ("chunk_a_size",
                              "__payload_chunk_a_size"
                              if args.chunk_a_size is None
                              else args.chunk_a_size)
        fields = [
            ("magic",          MAGIC),
            ("version",        VERSION),
            ("resident_dest",  "_bios_boot"),
            ("chunk_a_src",    args.chunk_a_src),
            chunk_a_size_field,
            ("chunk_b_src",    args.chunk_b_src),
            ("chunk_b_size",   "__payload_chunk_b_size"),
            ("cold_entry",     "_cpnos_cold_entry"),
            ("checksum_magic", CHECKSUM_MAGIC),
        ]
        fields += build_date_fields(args.build_date_str)
        fields += [
            ("scratch_bss_start", "__scratch_bss_start"),
            ("scratch_bss_end",   "__scratch_bss_end"),
            ("pio_rx_bss_start",  "__pio_rx_bss_start"),
            ("pio_rx_bss_end",    "__pio_rx_bss_end"),
        ]
        if args.include_ivt:
            fields += [
                ("ivt_start", "__ivt_start"),
                ("ivt_end",   "__ivt_end"),
            ]
        fields += [
            ("sentinel", SENTINEL),
            ("sentinel", SENTINEL),
        ]
        with open(args.out, "w") as out:
            fmt_sdcc(out, fields, emit_p1=args.emit_p1_header)
        print(f"gen_payload_header: wrote {args.out} (sdcc symbolic, "
              f"chunk_a_src={args.chunk_a_src:#06x} "
              f"chunk_b_src={args.chunk_b_src:#06x}, "
              f"build_date='{args.build_date_str}')")
        return 0

    # Non-symbolic SDCC: read map.
    if not args.map:
        p.error("--map required for --syntax=sdcc without --symbolic")
    if args.chunk_a_size is None:
        p.error("--chunk-a-size required for --syntax=sdcc without --symbolic")
    if not args.payload_bin:
        p.error("--payload-bin required for --syntax=sdcc without --symbolic")
    syms = read_symbols_from_map(args.map)

    def sym(name):
        if name not in syms:
            sys.exit(f"missing symbol in payload link: {name}")
        return syms[name]

    payload_size = os.path.getsize(args.payload_bin)
    chunk_a_size = args.chunk_a_size
    chunk_b_size = payload_size - chunk_a_size
    if chunk_b_size < 0:
        sys.exit(f"chunk-a-size {chunk_a_size} exceeds payload-bin size {payload_size}")

    fields = [
        ("magic",          MAGIC),
        ("version",        VERSION),
        ("resident_dest",  sym("_bios_boot")),
        ("chunk_a_src",    args.chunk_a_src if args.chunk_a_src is not None
                          else "__chunk_a_start"),
        ("chunk_a_size",   chunk_a_size),
        ("chunk_b_src",    args.chunk_b_src if args.chunk_b_src is not None
                          else "__chunk_b_start"),
        ("chunk_b_size",   chunk_b_size),
        ("cold_entry",     sym("_cpnos_cold_entry")),
        ("checksum_magic", CHECKSUM_MAGIC),
    ]
    fields += build_date_fields(args.build_date_str)
    fields += [
        ("scratch_bss_start", sym("__scratch_bss_start")),
        ("scratch_bss_end",   sym("__scratch_bss_end")),
        ("pio_rx_bss_start",  sym("__pio_rx_bss_start")),
        ("pio_rx_bss_end",    sym("__pio_rx_bss_end")),
    ]
    if args.include_ivt:
        fields += [
            ("ivt_start", sym("__ivt_start")),
            ("ivt_end",   sym("__ivt_end")),
        ]
    fields += [
        ("sentinel", SENTINEL),
        ("sentinel", SENTINEL),
    ]
    with open(args.out, "w") as out:
        fmt_sdcc(out, fields, emit_p1=args.emit_p1_header)
    print(f"gen_payload_header: wrote {args.out} (sdcc resolved, "
          f"chunk_a={chunk_a_size} chunk_b={chunk_b_size}, "
          f"payload_size={payload_size}, "
          f"build_date='{args.build_date_str}')")
    return 0


if __name__ == "__main__":
    sys.exit(main())
