#!/bin/sh
#
# regen_buildinfo_asm.sh OUT_INC
#
# Regenerate cpnos-in-asm's build/buildinfo.inc with the current
# local date + short git hash + dirty marker.  Output is a zmac
# include file holding a single `db "..."` of the build-info string.
# The cpnos-in-asm Makefile calls this via $(shell ...) at parse
# time so the .inc's mtime only changes when content differs (a
# .PHONY target would propagate rebuilds even when nothing changed).
#
# Mirrors cpnos-shared/scripts/regen_buildinfo.sh (the C-header
# variant cpnos-in-c uses); local-time choice + tmp-then-rename
# atomicity are identical.

set -e

OUT="$1"
[ -z "$OUT" ] && { echo "usage: $0 <out-inc>" >&2; exit 2; }

D=$(date +'%Y-%m-%d %H:%M')
H=$(git rev-parse --short HEAD 2>/dev/null || echo '????')
if ! git diff --quiet HEAD -- . 2>/dev/null; then H="${H}+"; fi

TMP="${OUT}.tmp"
mkdir -p "$(dirname "$OUT")"
{
    echo "; auto-generated by regen_buildinfo_asm.sh -- do not edit"
    printf '\tdb "%s %s"\n' "$D" "$H"
} > "$TMP"

if cmp -s "$TMP" "$OUT" 2>/dev/null; then
    rm -f "$TMP"
else
    mv "$TMP" "$OUT"
    echo "buildinfo-asm: $D $H" >&2
fi
