/* cpnos-rom payload header — data-driven relocator metadata.
 *
 * Emitted by both the clang and SDCC build pipelines into the PROM image
 * at a linker-decided offset (right after the relocator code).  The
 * relocator reads this header at boot to drive its work — no hardcoded
 * addresses in prom_loader.asm, no `--defsym` injection in the Makefile
 * relocator-link.
 *
 * Single source of truth for: where the resident lives in RAM, where the
 * chunks live in PROM and how big they are, where the cold entry is,
 * which BSS regions to zero before checksum verification, and the
 * checksum-magic constant.
 *
 * Adding a new BSS region or page-aligned reservation (IVT, future
 * buffers, etc.) requires touching exactly two files: the linker script
 * (defines the symbols + reservation) and the header generator script
 * (adds a pair to bss_pairs).  No Makefile change, no awk hop, no
 * cross-pipeline drift.
 *
 * Generated by tasks/scripts/gen_payload_header.py from payload.elf
 * (clang) or cpnos_payload.map (SDCC) at stage 2 of the build (after the
 * payload link, before the relocator link).
 */
#ifndef CPNOS_PAYLOAD_HEADER_H
#define CPNOS_PAYLOAD_HEADER_H

#include <stdint.h>

/* Magic number at the start of the header — readable as 'cP' (0x6350)
 * if you dump the binary.  Relocator checks this before believing the
 * rest of the header — catches a missing/corrupt header at boot rather
 * than executing into garbage.  Halts loudly on mismatch. */
#define PAYLOAD_HEADER_MAGIC   0x6350

/* Version — bumped if the layout below ever changes.  Relocator should
 * check (magic == MAGIC && version == VERSION) and halt otherwise so a
 * stale header from a previous build of the relocator catches itself. */
#define PAYLOAD_HEADER_VERSION 0x0001

/* Word-additive checksum target for the resident image (after relocator
 * has copied chunks to RAM).  Value is patched into the last 2 bytes of
 * the resident at link time by cpnos-build/patch_payload_checksum.py
 * such that the word-sum equals this magic.  Catches missing prom1.ic65,
 * bit rot, version mismatch — and a buggy BSS-clear extent that overran
 * its bounds (which is why the checksum runs AFTER the BSS-clear pass). */
#define PAYLOAD_CHECKSUM_MAGIC 0xCAFE

/* Sentinel that ends the bss_pairs list.  A pair whose start == this
 * value tells the relocator to stop iterating.  Real BSS regions never
 * land at 0xFFFE/0xFFFF — that's the top of the Z80 16-bit address
 * space, occupied by display memory and the wall-clock counter. */
#define PAYLOAD_BSS_SENTINEL   0xFFFFu

/* Header layout.  All fields are 16-bit little-endian (Z80 native).
 * The bss_pairs flexible array is iterated until a sentinel pair is
 * encountered. */
struct payload_header {
    uint16_t magic;            /* PAYLOAD_HEADER_MAGIC */
    uint16_t version;          /* PAYLOAD_HEADER_VERSION */

    /* Where the resident lives in RAM.  This is `_bios_boot` in the
     * payload link — the first byte of the BIOS jump table.  cpnos.com
     * hardcodes NIOS = resident_dest + 0x33 so the SNIOS jt lands
     * correctly; this address therefore can't move without touching
     * cpnos-build, but the linker still owns the symbol. */
    uint16_t resident_dest;

    /* Chunk A: copied first, lands at resident_dest. */
    uint16_t chunk_a_src;      /* PROM0 offset, linker-emitted */
    uint16_t chunk_a_size;     /* derived from dd-split boundary */

    /* Chunk B: copied second, lands at resident_dest + chunk_a_size. */
    uint16_t chunk_b_src;      /* PROM1 offset, linker-emitted */
    uint16_t chunk_b_size;     /* derived from payload_size − chunk_a_size */

    /* Cold entry — relocator JPs here after BSS clear + checksum.
     * Lives in PROM-resident `.init` region, runs in place from PROM
     * until `resident_handoff()` (in RAM) does the OUT (0x18) PROM
     * disable. */
    uint16_t cold_entry;

    /* Checksum magic the word-additive sum of the relocated payload
     * must equal.  Equals PAYLOAD_CHECKSUM_MAGIC; carried in the
     * header so a future build with a different magic is still
     * validated by the same relocator code. */
    uint16_t checksum_magic;

    /* Build date stamp, ASCII "YYYY-MM-DD HH:MM" (exactly 16 bytes,
     * no NUL).  Written to display memory at boot by the relocator so
     * the operator sees which build is being relocated BEFORE any
     * resident-code banner runs.  Also carried at PROM1 byte 0 in a
     * duplicate header so the relocator can detect cross-PROM
     * mismatch (PROM0 from build N-1 + PROM1 from build N) -- see
     * tasks/dual-header-plan-2026-05-08.md.  Field size is 16 bytes
     * (= 8 words) -- preserves the all-words-aligned header invariant
     * the word-additive checksum depends on. */
    char build_date_str[16];

    /* BSS regions to zero — variable-length, terminated by a pair
     * with start == PAYLOAD_BSS_SENTINEL.  Each pair is (start, end),
     * end exclusive (matches the C-array bound convention).  Today's
     * regions: scratch_bss, pio_rx_bss, ivt.  Future regions just
     * append a pair in the linker script + header generator. */
    uint16_t bss_pairs[][2];
};

#endif /* CPNOS_PAYLOAD_HEADER_H */
