#!/bin/bash
# install-cpm86-target.sh -- INSTALLATION STEP that makes Open Watcom practical as
# a CP/M-86 (RC759) cross-compiler by generating a Watcom-side "target support"
# directory from DR C 1.11's files. DR C's own files are NEVER modified -- this
# only READS CLEARL's export table and EMITS glue into the Watcom tree.
#
# What it installs into  $CPM86_TARGET_DIR  (default: open-watcom-v2/cpm86):
#   _preincl.h   Auto-included by bwcc (Watcom's default pre-include name) whenever
#                that dir is on the -i path. It defines the DR C large-model calling
#                convention (`DRC`), the DRC_MAIN entry macro, and one
#                `#pragma aux (DRC) fn;` for every PUBLIC DR C stdlib routine, so a
#                user program needs NO bridge pragmas at all -- selecting the target
#                (cc-cpm86.sh, which puts this dir on -i) loads the glue.
#   WMARKS.OBJ   Classicized stub for Watcom's model markers (_big_code_ /
#                _small_code_ = 0), ready to hand to LINK-86.
#
# The set of DRC-convention symbols is derived from CLEARL.L86 itself (the actual
# stdlib), so it stays in sync with DR C without touching DR C's headers.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
OW="${OW:-$HERE/../open-watcom-v2/build/binbuild}"
DRC="${DRC:-$HERE/drc86111}"
CPM86_TARGET_DIR="${CPM86_TARGET_DIR:-$HERE/../open-watcom-v2/cpm86}"
[ -x "$OW/bwasm" ] || { echo "Open Watcom not built at $OW"; exit 1; }
[ -f "$DRC/CLEARL.L86" ] || { echo "DR C CLEARL.L86 not found at $DRC"; exit 1; }

mkdir -p "$CPM86_TARGET_DIR"
PRE="$CPM86_TARGET_DIR/_preincl.h"

# Symbols that are exported by CLEARL but must NOT get the call convention:
#   main        -- the entry symbol we alias drc_main TO (not a callee)
#   errno,sys_nerr -- data objects, not routines
#   nostart,nofloat,clear_error -- link-control / 8087 internals
BLOCK=" main errno sys_nerr nostart nofloat clear_error "

# Extract public (no leading underscore) libc-looking symbols from the real stdlib.
SYMS=$(strings "$DRC/CLEARL.L86" | grep -oE '^[a-z][a-z0-9_]{1,10}$' | grep -vE '^_' | sort -u)

{
  echo "/* _preincl.h -- GENERATED by install-cpm86-target.sh from DR C's CLEARL.L86."
  echo " * Do not edit by hand; re-run the installer to regenerate. DR C files are"
  echo " * untouched -- this is Watcom-side glue auto-loaded for the CP/M-86 target."
  echo " *"
  echo " * Provides: the DR C large-model calling convention (DRC), the DRC_MAIN entry"
  echo " * macro, and a #pragma aux (DRC) line for every public DR C stdlib routine."
  echo " * Compile via cc-cpm86.sh (adds this dir to -i, so this file auto-includes)."
  echo " */"
  echo "#ifndef _CPM86_PREINCL_H"
  echo "#define _CPM86_PREINCL_H"
  echo ""
  echo "/* DR C large-model cdecl: args pushed right-to-left, caller cleans, return"
  echo " * in AX (DX:AX for long), far call. \"*\" alias -> bare DR C symbol name. */"
  echo "#pragma aux DRC \"*\" parm caller [] value [ax] far;"
  echo ""
  echo "/* Entry point: define your program with  DRC_MAIN { ... }. Exported as the"
  echo " * bare far symbol \"main\" that DR C's CLEARL startup calls. Named drc_main"
  echo " * (not main) so Watcom does not drag in its own _cstart_ startup. */"
  echo "void drc_main(void);"
  echo "#pragma aux drc_main \"main\" far;"
  echo "#define DRC_MAIN void drc_main(void)"
  echo ""
  echo "/* DRC convention applied to each public DR C stdlib routine (from CLEARL). */"
  for s in $SYMS; do
    case "$BLOCK" in *" $s "*) continue;; esac
    echo "#pragma aux (DRC) $s;"
  done
  echo ""
  echo "#endif /* _CPM86_PREINCL_H */"
} > "$PRE"

# Marker stub -> classicized OBJ ready for LINK-86.
cat > "$CPM86_TARGET_DIR/wmarks.asm" <<'ASM'
        public _big_code_
        public _small_code_
_big_code_   equ 0
_small_code_ equ 0
        end
ASM
"$OW/bwasm" -q -fo="$CPM86_TARGET_DIR/WMARKS.OBJ" "$CPM86_TARGET_DIR/wmarks.asm"
python3 "$HERE/omf_classicize.py" "$CPM86_TARGET_DIR/WMARKS.OBJ" "$CPM86_TARGET_DIR/WMARKS.OBJ" >/dev/null

N=$(grep -c "pragma aux (DRC)" "$PRE")
echo "Installed CP/M-86 Watcom target support -> $CPM86_TARGET_DIR"
echo "  _preincl.h : DRC convention + DRC_MAIN + $N stdlib pragmas (from CLEARL.L86)"
echo "  WMARKS.OBJ : model-marker stub (classicized)"
echo "DR C files under $DRC were NOT modified."
