#!/bin/bash
# install-cpm86-target.sh -- INSTALLATION STEP that makes Open Watcom practical as
# a CP/M-86 (RC759) cross-compiler by generating a Watcom-side "target support"
# directory from DR C 1.11's files. DR C's own files are NEVER modified -- this
# only READS CLEARL's export table and EMITS glue into the Watcom tree.
#
# What it installs into  $CPM86_TARGET_DIR  (default: open-watcom-v2/cpm86):
#   _preincl.h   Auto-included by bwcc (Watcom's default pre-include name) whenever
#                that dir is on the -i path. It defines the DR C large-model calling
#                convention (`DRC`), the DRC_MAIN entry macro, and one
#                `#pragma aux (DRC) fn;` for every PUBLIC DR C stdlib routine, so a
#                user program needs NO bridge pragmas at all -- selecting the target
#                (cc-cpm86.sh, which puts this dir on -i) loads the glue.
#   WMARKS.OBJ   Classicized stub for Watcom's model markers (_big_code_ /
#                _small_code_ = 0), ready to hand to LINK-86.
#
# The set of DRC-convention symbols is derived from CLEARL.L86 itself (the actual
# stdlib), so it stays in sync with DR C without touching DR C's headers.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
OW="${OW:-$HERE/../open-watcom-v2/build/binbuild}"
DRC="${DRC:-$HERE/drc86111}"
CPM86_TARGET_DIR="${CPM86_TARGET_DIR:-$HERE/../open-watcom-v2/cpm86}"
[ -x "$OW/bwasm" ] || { echo "Open Watcom not built at $OW"; exit 1; }
[ -f "$DRC/CLEARL.L86" ] || { echo "DR C CLEARL.L86 not found at $DRC"; exit 1; }

mkdir -p "$CPM86_TARGET_DIR"
PRE="$CPM86_TARGET_DIR/_preincl.h"

# Symbols that are exported by CLEARL but must NOT get the call convention:
#   main        -- the entry symbol we alias drc_main TO (not a callee)
#   errno,sys_nerr -- data objects, not routines
#   nostart,nofloat,clear_error -- link-control / 8087 internals
BLOCK=" main errno sys_nerr nostart nofloat clear_error "

# Extract public (no leading underscore) libc-looking symbols from the real
# stdlib. Take the UNION of both models' libraries (CLEARS small + CLEARL large)
# so the generated glue serves either model; the names are identical libc names.
SYMS=$( { strings -n 3 "$DRC/CLEARL.L86"; [ -f "$DRC/CLEARS.L86" ] && strings -n 3 "$DRC/CLEARS.L86"; } \
        | grep -oE '^[a-z][a-z0-9_]{1,10}$' | grep -vE '^_' | sort -u)

{
  echo "/* _preincl.h -- GENERATED by install-cpm86-target.sh from DR C's CLEAR*.L86."
  echo " * Do not edit by hand; re-run the installer to regenerate. DR C files are"
  echo " * untouched -- this is Watcom-side glue auto-loaded for the CP/M-86 target."
  echo " *"
  echo " * Provides: the DR C calling convention (DRC), the DRC_MAIN entry macro,"
  echo " * and a #pragma aux (DRC) line for every public DR C stdlib routine."
  echo " * Compile via cc-cpm86.sh (adds this dir to -i, so this file auto-includes)."
  echo " */"
  echo "#ifndef _CPM86_PREINCL_H"
  echo "#define _CPM86_PREINCL_H"
  echo ""
  echo "/* DR C cdecl: args pushed right-to-left, caller cleans.  The RETURN"
  echo " * register differs by type and MUST match DR C (verified by disassembling"
  echo " * CLEARL/CLEARS modules -- this is a COMPILER-WIDE convention, uniform by"
  echo " * return type, NOT per function):"
  echo " *   int / char / near ptr -> AX            (Watcom default: matches)"
  echo " *   large-model far ptr    -> BX:AX        (seg=BX off=AX; Watcom DX:AX: MISMATCH)"
  echo " *   long / float           -> BX:AX        (Watcom default DX:AX: MISMATCH)"
  echo " *   double                 -> DX:CX:BX:AX  (Watcom default AX:BX:CX:DX: MISMATCH)"
  echo " * So the plain DRC alias (no value clause) is correct ONLY for int and"
  echo " * near-ptr (small-model) returns; far-ptr / long / double returns use the"
  echo " * DRC_PTR / DRC_LONG / DRC_DBL aliases below, which pin DR C's value"
  echo " * registers. Far pointers need TWO registers (value [bx ax]); a single"
  echo " * value [ax] on a far-ptr return is rejected E1121 -- so we split by return"
  echo " * type, never force value [ax] on the generic alias. Return REGISTERS are"
  echo " * proven by bwdis (0INDEX/0STRN: 'mov bx,es; mov ax,..; retf' => far ptr"
  echo " * BX:AX); return TYPES come from DR C's own STDIO.H. Call is FAR in large,"
  echo " * NEAR in small; \"*\" alias -> bare DR C symbol name. */"
  echo "#ifdef __LARGE__"
  echo "#pragma aux DRC      \"*\" parm caller [] far;"
  echo "#pragma aux DRC_PTR  \"*\" parm caller [] value [bx ax] far;"
  echo "#pragma aux DRC_LONG \"*\" parm caller [] value [bx ax] far;"
  echo "#pragma aux DRC_DBL  \"*\" parm caller [] value [dx cx bx ax] far;"
  echo "#else"
  echo "#pragma aux DRC      \"*\" parm caller [];"
  echo "#pragma aux DRC_PTR  \"*\" parm caller [];"
  echo "#pragma aux DRC_LONG \"*\" parm caller [] value [bx ax];"
  echo "#pragma aux DRC_DBL  \"*\" parm caller [] value [dx cx bx ax];"
  echo "#endif"
  echo ""
  echo "/* Entry point: define your program with  DRC_MAIN { ... }. Exported as the"
  echo " * bare symbol \"main\" that DR C's startup calls (far in large, near in"
  echo " * small). Named drc_main (not main) so Watcom does not drag in _cstart_. */"
  echo "void drc_main(void);"
  echo "#ifdef __LARGE__"
  echo "#pragma aux drc_main \"main\" far;"
  echo "#else"
  echo "#pragma aux drc_main \"main\";"
  echo "#endif"
  echo "#define DRC_MAIN void drc_main(void)"
  echo ""
  echo "/* DRC convention applied to each public DR C stdlib routine (from CLEARL)."
  echo " * Return-register override by type: far ptr via DRC_PTR (BX:AX large /"
  echo " * AX small), long/float via DRC_LONG (BX:AX), double via DRC_DBL"
  echo " * (DX:CX:BX:AX); all others use the plain DRC alias. Return TYPES are read"
  echo " * from DR C's STDIO.H; the register mapping is the compiler-wide convention"
  echo " * proven by disassembling CLEARL modules. Extend a set only after confirming"
  echo " * the routine's return type in DR C's header (or by disassembly)."
  echo " *"
  echo " * Each PTR/LONG/DBL routine gets a matching PROTOTYPE emitted right next to"
  echo " * its pragma: the value-register override (value [bx ax] etc.) only takes"
  echo " * effect if the compiler also knows the return WIDTH. Co-locating prototype"
  echo " * + pragma here makes this file the single source of truth for BOTH, so the"
  echo " * return type and its register mapping can never drift apart (the class of"
  echo " * bug that hid the far-ptr BX:AX / long BX:AX / double DX:CX:BX:AX mismatch)."
  echo " * A far ptr is 4 bytes regardless of pointee, so char* stands in for FILE*."
  echo " * These prototypes are seen only by Watcom (this file is auto-included via"
  echo " * bwcc -i); genuine DR C uses its own headers and never sees them. */"
  # Pointer-returning (char*/FILE*/void*) -> far ptr BX:AX (large) / AX (small).
  # Types from DR C STDIO.H: calloc/malloc/realloc/zalloc/sbrk/gets/fgets/index/
  # rindex/strchr/strrchr/strcat/strncat/strcpy/strncpy (char*); fopen/fopena/
  # fopenb (FILE*). fdopen/freop*/fopen-variants are the same family; mktemp/
  # getpass/ttyname* return char*.
  DRC_PTR_FNS=" calloc malloc realloc zalloc sbrk gets fgets index rindex strchr strrchr strcat strncat strcpy strncpy fopen fopena fopenb fopenax fopend fdopen freopen freopa freopb freopbb freopen4 mktemp getpass ttyname ttynamez "
  # Long-returning (BX:AX). Types from STDIO.H: atol/lseek/ftell/tell/getl/putl.
  DRC_LONG_FNS=" atol ftell tell lseek getl putl "
  # Double-returning (DX:CX:BX:AX). Types from STDIO.H:
  # atof/sqrt/cos/sin/exp/fabs/tan/atan; log/log10 by convention.
  DRC_DBL_FNS=" atof sqrt cos sin exp fabs tan atan log log10 "
  for s in $SYMS; do
    case "$BLOCK" in *" $s "*) continue;; esac
    case "$DRC_DBL_FNS"  in *" $s "*) printf 'extern double %s();\n#pragma aux (DRC_DBL)  %s;\n' "$s" "$s"; continue;; esac
    case "$DRC_LONG_FNS" in *" $s "*) printf 'extern long   %s();\n#pragma aux (DRC_LONG) %s;\n' "$s" "$s"; continue;; esac
    case "$DRC_PTR_FNS"  in *" $s "*) printf 'extern char  *%s();\n#pragma aux (DRC_PTR)  %s;\n' "$s" "$s"; continue;; esac
    echo "#pragma aux (DRC) $s;"
  done
  echo ""
  echo "#endif /* _CPM86_PREINCL_H */"
} > "$PRE"

# Marker stub -> classicized OBJ ready for LINK-86.
cat > "$CPM86_TARGET_DIR/wmarks.asm" <<'ASM'
        public _big_code_
        public _small_code_
_big_code_   equ 0
_small_code_ equ 0
        end
ASM
"$OW/bwasm" -q -fo="$CPM86_TARGET_DIR/WMARKS.OBJ" "$CPM86_TARGET_DIR/wmarks.asm"
python3 "$HERE/omf_classicize.py" "$CPM86_TARGET_DIR/WMARKS.OBJ" "$CPM86_TARGET_DIR/WMARKS.OBJ" >/dev/null

N=$(grep -c "pragma aux (DRC)" "$PRE")
echo "Installed CP/M-86 Watcom target support -> $CPM86_TARGET_DIR"
echo "  _preincl.h : DRC convention + DRC_MAIN + $N stdlib pragmas (from CLEARL.L86)"
echo "  WMARKS.OBJ : model-marker stub (classicized)"
echo "DR C files under $DRC were NOT modified."
